### ISSUE TITLE
Make phptags available on packagist

### ISSUE THREAD

**Issue by jorissteyn** [jorissteyn/phptags#1]
A remark from @periklis in https://github.com/ejmr/php-mode/issues/235:
1. PHPTags missing from packagist in order to use it in my global composer.json. I am using a composer based installation for php tooling like phpunit/php-refactor/etc. in my home directory.

**Comment by jorissteyn** [comment]
Done!

https://packagist.org/packages/jorissteyn/phptags

**Comment by periklis** [comment]
Fine job! One missing point still. The package does not link the script `jorissteyn/phptags/bin/phptags` under `vendor/bin/phptags`. Latter is best practice to put in the PATH.

**Comment by jorissteyn** [comment]
Ah  I see. I now registered the executable in composer.json and changed the way the autoloader was included, works standalone and as part of another package.
